baseurl: "http://andygrunwald.com/"
languageCode: "en-us"
title: "Andy Grunwald"
theme: "hugo-type-theme"
disqusShortname: "andygrunwald"
googleAnalytics: "UA-64342623-1"
# Posts per page
paginate: 10
permalinks:
  post: /blog/:title/

params:
  author: "Andy Grunwald"
  description: "Andy Grunwald - Software Engineer from Germany"
  keywords: "backend,infrastructure,operations,devops,computer science,web development"
  copyright: "Andy Grunwald"
  headerText: "Hi, my name is **Andy Grunwald**, a Software Engineer from Germany with a focus on **Backend and Infrastructure**. I am leading the Software Operations Team at [trivago](http://www.trivago.com/)."
  gravatar: "andygrunwald@gmail.com"
  social:
    email: "andygrunwald@gmail.com"
    github: "andygrunwald"
    linkedin: "https://www.linkedin.com/in/andy-grunwald-09aa265a"
    twitter: "andygrunwald"